apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: investment-funnel-app-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: investment-funnel-app
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # scaledown no more than 1 pod per 1 minute
      selectPolicy: Min
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # same rule as for scaling down
        - type: Percent
          value: 12
          periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Value
          averageValue: "500m"
