apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-funnel-app
  labels:
    app: investment-funnel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-funnel-app
  template:
    metadata:
      labels:
        app: investment-funnel-app
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 65534
      containers:
        - name: investment-funnel-app
          image: investment-funnel-app
          ports:
            - containerPort: 8050
          resources:
            limits:
              memory: 1500Mi
              cpu: "0.5"
            requests:
              memory: 1000Mi
              cpu: "0.3"
          livenessProbe:
            httpGet:
              path: /health
              port: 8050
            initialDelaySeconds: 1800
            timeoutSeconds: 30
            periodSeconds: 1200
          readinessProbe:
            httpGet:
              path: /health
              port: 8050
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 30
          env:
            - name: CLOUD_LOGGING
              value: "True"
            - name: GCS_BUCKET_ID
              value: TODO
            - name: TOKENIZERS_PARALLELISM
              value: "false"
            - name: ENVIRONMENT
              value: TODO
          command:
            ["gunicorn", "-b 0.0.0.0:8050", "-t 600", "app:server"]
