apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - autoscale.yaml
  - service.yaml
images:
  - name: investment-funnel-app
    newName: TODO/investment-funnel-app
    newTag: v0.0.1
