apiVersion: v1
kind: Service
metadata:
  name: investment-funnel-app
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: investment-funnel-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8050
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
